name: 📋 Phase Planning
description: Plan a development phase with multiple related issues
title: "[Phase]: "
labels: ["status: needs-planning", "component: documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to plan a development phase that includes multiple related issues or features.

  - type: input
    id: phase-name
    attributes:
      label: Phase Name
      description: What is this development phase called?
      placeholder: "Phase X: Description"
    validations:
      required: true

  - type: textarea
    id: phase-objectives
    attributes:
      label: Phase Objectives
      description: What are the main goals and objectives of this phase?
      placeholder: |
        - Objective 1
        - Objective 2
        - Objective 3
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How will we know this phase is successfully completed?
      placeholder: |
        - [ ] Success criteria 1
        - [ ] Success criteria 2
        - [ ] Success criteria 3
    validations:
      required: true

  - type: textarea
    id: included-issues
    attributes:
      label: Included Issues
      description: List the issues that will be addressed in this phase
      placeholder: |
        - #123 - Issue description
        - #124 - Issue description
        - #125 - Issue description
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Estimated Timeline
      description: How long do you estimate this phase will take?
      placeholder: "2-3 weeks"
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: Testing Requirements
      description: What testing will be required for this phase?
      placeholder: |
        - Unit tests for new functionality
        - Integration tests for database changes
        - Playwright tests for UI changes
        - Manual testing checklist

  - type: textarea
    id: documentation-needs
    attributes:
      label: Documentation Requirements
      description: What documentation will need to be created or updated?
      placeholder: |
        - API documentation
        - User guide updates
        - Developer documentation
        - CLAUDE.md updates

  - type: textarea
    id: risk-assessment
    attributes:
      label: Risk Assessment
      description: What are the potential risks or challenges for this phase?
      placeholder: |
        - Risk 1 and mitigation strategy
        - Risk 2 and mitigation strategy
        - Risk 3 and mitigation strategy

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies or prerequisites for this phase?
      placeholder: External APIs, library updates, infrastructure changes, etc.

  - type: dropdown
    id: phase-priority
    attributes:
      label: Phase Priority
      description: How urgent is this development phase?
      options:
        - Low - Future consideration
        - Medium - Planned development
        - High - Priority development
        - Critical - Immediate development required
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true