<?php

declare(strict_types=1);

use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\TestCase;

/**
 * Confirms app/api/shared/join-failure-report.php (the Issue #1690
 * client-side failure beacon) and usersc/join.php's real registration flow
 * use two SEPARATE rate-limit buckets ('join_failure_beacon' and
 * 'registration_attempt' respectively) rather than one shared bucket.
 *
 * (File renamed from JoinFailureReportSharesRateLimitBucketTest.php to
 * match — see git history for the original name/rationale.)
 *
 * Why separate buckets: 'registration_attempt' is tight (ip_max=5/hr) and
 * IP-scoped, so beacon traffic (Turnstile retries, GPS failures, JS
 * exceptions — none of them a real registration attempt) sharing it could
 * exhaust the cap for every visitor behind a shared/NAT IP before any of
 * them could actually submit the form — a lockout vector the original
 * single-POST join.php never exposed this cheaply. The beacon uses its own,
 * higher-ceiling config instead (see usersc/includes/rate_limits.php).
 *
 * Why this is a source-text test rather than a live-request integration
 * test: checkRateLimit() is called with no explicit identifiers at either
 * call site — RateLimit::check() derives the IP identifier internally (see
 * users/classes/RateLimit.php) — and this repo's IntegrationTestCase has no
 * multi-IP request-simulation harness (see
 * tests/integration/IntegrationTestCase.php). Asserting the two files use
 * DIFFERENT literal action strings is the one fact that actually determines
 * bucket separation, since RateLimit scopes all counting by (action,
 * identifiers).
 *
 * @issue 1690
 * @link https://github.com/elan-registry/registry/issues/1690
 */
#[Group('regression')]
#[Group('fast')]
final class JoinFailureReportUsesDedicatedRateLimitBucketTest extends TestCase
{
    private const JOIN_PHP_PATH = __DIR__ . '/../../usersc/join.php';
    private const BEACON_PATH = __DIR__ . '/../../app/api/shared/join-failure-report.php';
    private const CONFIG_PATH = __DIR__ . '/../../usersc/includes/rate_limits.php';

    public function testBeaconUsesItsOwnDedicatedRateLimitAction(): void
    {
        $beaconSource = file_get_contents(self::BEACON_PATH);
        $this->assertIsString($beaconSource, 'app/api/shared/join-failure-report.php must be readable');

        $this->assertStringContainsString(
            "checkRateLimit('join_failure_beacon')",
            $beaconSource,
            'The beacon must check its own join_failure_beacon rate limit, not registration_attempt — '
                . 'sharing the tight registration_attempt bucket (ip_max=5/hr) would let beacon traffic '
                . 'exhaust it for every visitor behind a shared/NAT IP'
        );

        $this->assertStringNotContainsString(
            "checkRateLimit('registration_attempt')",
            $beaconSource,
            'The beacon must not check registration_attempt — that bucket belongs to the real '
                . 'registration flow in join.php and must not be shared with beacon traffic'
        );
    }

    public function testJoinPhpStillUsesRegistrationAttemptForTheRealFlow(): void
    {
        $joinSource = file_get_contents(self::JOIN_PHP_PATH);
        $this->assertIsString($joinSource, 'usersc/join.php must be readable');

        $this->assertStringContainsString(
            "checkRateLimit('registration_attempt')",
            $joinSource,
            'usersc/join.php must still check the registration_attempt rate limit for real submissions'
        );
    }

    /**
     * Neither call site should pass extra identifiers that would further
     * split either bucket beyond the single IP-derived identifier each
     * action already uses.
     */
    public function testNeitherCallSiteAddsExtraIdentifiers(): void
    {
        $joinSource = file_get_contents(self::JOIN_PHP_PATH);
        $this->assertIsString($joinSource);

        $beaconSource = file_get_contents(self::BEACON_PATH);
        $this->assertIsString($beaconSource);

        $this->assertStringNotContainsString(
            "checkRateLimit('registration_attempt', ",
            $joinSource,
            'join.php must not pass extra identifiers to the registration_attempt check'
        );

        $this->assertStringNotContainsString(
            "checkRateLimit('join_failure_beacon', ",
            $beaconSource,
            'The beacon must not pass extra identifiers to the join_failure_beacon check'
        );
    }

    /**
     * Both actions must actually be configured — a missing entry would mean
     * checkRateLimit() silently no-ops for that action at runtime.
     *
     * Loads the config directly rather than grepping its source text: the
     * project-owned usersc/includes/rate_limits.php is regenerated by the
     * in-app Rate Limiting Dashboard, which writes per-key assignments
     * ($rateLimits['action']['key'] = value;) rather than the array-literal
     * syntax ('action' => [...]) this test originally matched against — a
     * source-text assertion breaks on every dashboard save regardless of
     * whether the actual values are correct.
     */
    public function testExactlyOneConfigEntryExistsPerAction(): void
    {
        $rateLimits = $this->loadRateLimits();

        $this->assertArrayHasKey(
            'registration_attempt',
            $rateLimits,
            'registration_attempt must be configured in usersc/includes/rate_limits.php'
        );

        $this->assertArrayHasKey(
            'join_failure_beacon',
            $rateLimits,
            'join_failure_beacon must be configured in usersc/includes/rate_limits.php'
        );
    }

    /**
     * The beacon's bucket must be strictly more permissive than the real
     * registration flow's — it exists specifically to avoid the lockout
     * risk of a tight shared cap, so a regression that tightens it back
     * down (or loosens registration_attempt past it) should fail loudly.
     */
    public function testBeaconLimitIsMorePermissiveThanRegistrationAttempt(): void
    {
        $rateLimits = $this->loadRateLimits();

        $this->assertArrayHasKey('registration_attempt', $rateLimits);
        $this->assertArrayHasKey('join_failure_beacon', $rateLimits);
        $this->assertArrayHasKey('ip_max', $rateLimits['registration_attempt']);
        $this->assertArrayHasKey('ip_max', $rateLimits['join_failure_beacon']);

        $this->assertGreaterThan(
            $rateLimits['registration_attempt']['ip_max'],
            $rateLimits['join_failure_beacon']['ip_max'],
            'join_failure_beacon.ip_max must be strictly greater than registration_attempt.ip_max — '
                . 'the whole point of separating them is a higher ceiling for beacon traffic'
        );
    }

    /**
     * @return array<string, array<string, int>>
     */
    private function loadRateLimits(): array
    {
        $rateLimits = [];
        require self::CONFIG_PATH;

        $this->assertIsArray($rateLimits, 'usersc/includes/rate_limits.php must populate $rateLimits');

        return $rateLimits;
    }
}
