<?php

/*
 * phpMyEdit language file
 *
 * language: hungarian
 * encoding: iso-8859-2
 * date: 2010-04-01
 * author: János Molnár <molnarj80@gmail.com>
 */

/* $Platon: phpMyEdit/lang/PME.lang.HU.inc,v 1.1 2010/04/02 09:58:17 nepto Exp $ */

return Array(
		'Add'           	=>'Hozzáad',
		'Copy'           	=>'Másol',
		'Change'        	=>'Változtat',
		'Delete'        	=>'Töröl',
		'View'  	   	 	=>'Megtekint',
		'Prev'          	=>'Elõzõ',
		'Next'          	=>'Következõ',
		'First'         	=>'Elsõ',
		'Last'          	=>'Utólsó',
		'Go to'         	=>'Ugor',
		'Page'          	=>'Lap',
		'Records'       	=>'Sorok száma',
		'Save'          	=>'Ment',
		'More'          	=>'Több',
		'Apply'         	=>'Alkalmaz',
		'Cancel'        	=>'Mégsem',
		'Search'			=>'Keres',
		'Hide'				=>'Elrejt',
		'Clear'				=>'Ürít',
		'Query'				=>'Lekérdezés',
		'Current Query'		=>'Aktuális lekérdezés',
		'Sorted By'			=>'Rendezés',
		'ascending'			=>'növekvõ',
		'descending'		=>'csökkenõ',
		'hidden'			=>'rejtett',
		'of'				=>'/',
		'record added'  	=>'sor hozzáadva',
		'record changed'	=>'sor megváltoztatva',
		'record deleted'	=>'sor törölve',
		'Please enter'  	=>'Töltse ki',
		'months' => Array(
			'01'=>'Január',
			'02'=>'Február',
			'03'=>'Március',
			'04'=>'Április',
			'05'=>'Május',
			'06'=>'Június',
			'07'=>'Július',
			'08'=>'Augusztus',
			'09'=>'Szeptember',
			'10'=>'Október',
			'11'=>'November',
			'12'=>'December'),
		// phpMyEdit-report
		'Make report'			=> 'Riport készítés',
		'Select fields'			=> 'Válassza ki a mezõket',
		'Records per screen'	=> 'Sor / képernyõ',
		);

?>
