<?php

/**
 * phpMyEdit language file
 *
 * language: hebrew (Israel)
 * encoding: UTF-8
 * date: 2007-11, 2007-11-11
 * author: Shula <makorepolaazazel@yahoo.com>
 */

/* $Platon: phpMyEdit/lang/PME.lang.HE-IL-UTF8.inc,v 1.1 2007/12/18 07:53:16 michal Exp $ */

return Array(
		'Add'           	=>'הוסף',
		'Copy'           	=>'העתק',
		'Change'       		=>'שינוי',
		'Delete'        	=>'מחק',
		'View'	     	 	=>'הצג',
		'Prev'          	=>'הקודם',
		'Next'          	=>'הבא',
		'First'         	=>'ראשון',
		'Last'          	=>'אחרון',
		'Go to'         	=>'עבור אל',
		'Page'          	=>'עמוד',
		'Records'       	=>'רשומות',
		'Save'          	=>'שמור',
		'More'          	=>'עוד',
		'Apply'         	=>'החל',
		'Cancel'        	=>'בטל',
		'Search'		=>'חפש',
		'Hide'			=>'הסתר',
		'Clear'			=>'מחק',
		'Query'			=>'שאילתה',
		'Current Query'		=>'שאילתה נוכחית',
		'Sorted By'		=>'ממוין לפי',
		'ascending'		=>'עולה',
		'descending'		=>'יורד',
		'hidden'		=>'מוסתר',
		'of'			=>'מתוך',
		'record added'  	=>'רשומה נוספה',
		'record changed'	=>'רשומה עודכנה',
		'record deleted'	=>'רשומה נמחקה',
		'Please enter'  	=>'אנא הכנס',
		'months' => Array(
			'01'	=>	'ינואר',
			'02'	=>	'פברואר',
			'03'	=>	'מרץ',
			'04'	=>	'אפריל',
			'05'	=>	'מאי',
			'06'	=>	'יוני',
			'07'	=>	'יולי',
			'08'	=>	'אוגוסט',
			'09'	=>	'ספטמבר',
			'10'	=>	'אוקטובר',
			'11'	=>	'נובמבר',
			'12'	=>	'דצמברר'),
		// phpMyEdit-report
		'Make report'		=> 'בצע ד"וח',
		'Select fields'		=> 'בחר שדות',
		'Records per screen'	=> 'רשומות לכל מסך',
		);

?>