<?php
/**
 * Custom Rate Limits Configuration
 * Generated by UserSpice Rate Limiting Dashboard
 * Last updated: 2026-08-25 15:43:05
 */

$rateLimits['login_attempt']['ip_max'] = 50;
$rateLimits['login_attempt']['ip_window'] = 900;
$rateLimits['login_attempt']['user_max'] = 10;
$rateLimits['login_attempt']['user_window'] = 300;
$rateLimits['login_attempt']['total_max'] = 100;
$rateLimits['login_attempt']['total_window'] = 900;

$rateLimits['totp_verify']['ip_max'] = 50;
$rateLimits['totp_verify']['ip_window'] = 300;
$rateLimits['totp_verify']['user_max'] = 25;
$rateLimits['totp_verify']['user_window'] = 300;
$rateLimits['totp_verify']['total_max'] = 100;
$rateLimits['totp_verify']['total_window'] = 300;

$rateLimits['totp_verify_and_activate']['ip_max'] = 50;
$rateLimits['totp_verify_and_activate']['ip_window'] = 300;
$rateLimits['totp_verify_and_activate']['user_max'] = 25;
$rateLimits['totp_verify_and_activate']['user_window'] = 300;
$rateLimits['totp_verify_and_activate']['total_max'] = 100;
$rateLimits['totp_verify_and_activate']['total_window'] = 300;

$rateLimits['totp_regenerate_backup_codes']['ip_max'] = 50;
$rateLimits['totp_regenerate_backup_codes']['ip_window'] = 300;
$rateLimits['totp_regenerate_backup_codes']['user_max'] = 25;
$rateLimits['totp_regenerate_backup_codes']['user_window'] = 300;
$rateLimits['totp_regenerate_backup_codes']['total_max'] = 100;
$rateLimits['totp_regenerate_backup_codes']['total_window'] = 300;

$rateLimits['passkey_register']['ip_max'] = 50;
$rateLimits['passkey_register']['ip_window'] = 300;
$rateLimits['passkey_register']['user_max'] = 25;
$rateLimits['passkey_register']['user_window'] = 300;
$rateLimits['passkey_register']['total_max'] = 100;
$rateLimits['passkey_register']['total_window'] = 300;

$rateLimits['passkey_verify']['ip_max'] = 30;
$rateLimits['passkey_verify']['ip_window'] = 600;
$rateLimits['passkey_verify']['user_max'] = 10;
$rateLimits['passkey_verify']['user_window'] = 600;
$rateLimits['passkey_verify']['credential_max'] = 6;
$rateLimits['passkey_verify']['credential_window'] = 900;
$rateLimits['passkey_verify']['total_max'] = 50;
$rateLimits['passkey_verify']['total_window'] = 900;

$rateLimits['passkey_store']['ip_max'] = 50;
$rateLimits['passkey_store']['ip_window'] = 300;
$rateLimits['passkey_store']['user_max'] = 25;
$rateLimits['passkey_store']['user_window'] = 300;
$rateLimits['passkey_store']['total_max'] = 100;
$rateLimits['passkey_store']['total_window'] = 300;

$rateLimits['passkey_auth']['ip_max'] = 50;
$rateLimits['passkey_auth']['ip_window'] = 300;
$rateLimits['passkey_auth']['user_max'] = 25;
$rateLimits['passkey_auth']['user_window'] = 300;
$rateLimits['passkey_auth']['total_max'] = 100;
$rateLimits['passkey_auth']['total_window'] = 300;

$rateLimits['passkey_diagnostics']['ip_max'] = 50;
$rateLimits['passkey_diagnostics']['ip_window'] = 300;
$rateLimits['passkey_diagnostics']['user_max'] = 25;
$rateLimits['passkey_diagnostics']['user_window'] = 300;
$rateLimits['passkey_diagnostics']['total_max'] = 100;
$rateLimits['passkey_diagnostics']['total_window'] = 300;

$rateLimits['passkey_network-test']['ip_max'] = 50;
$rateLimits['passkey_network-test']['ip_window'] = 300;
$rateLimits['passkey_network-test']['user_max'] = 25;
$rateLimits['passkey_network-test']['user_window'] = 300;
$rateLimits['passkey_network-test']['total_max'] = 100;
$rateLimits['passkey_network-test']['total_window'] = 300;

$rateLimits['password_reset_request']['ip_max'] = 20;
$rateLimits['password_reset_request']['ip_window'] = 3600;
$rateLimits['password_reset_request']['email_max'] = 5;
$rateLimits['password_reset_request']['email_window'] = 3600;
$rateLimits['password_reset_request']['total_max'] = 30;
$rateLimits['password_reset_request']['total_window'] = 3600;

$rateLimits['password_reset_submit']['ip_max'] = 50;
$rateLimits['password_reset_submit']['ip_window'] = 300;
$rateLimits['password_reset_submit']['token_max'] = 4;
$rateLimits['password_reset_submit']['token_window'] = 1800;
$rateLimits['password_reset_submit']['total_max'] = 100;
$rateLimits['password_reset_submit']['total_window'] = 300;

$rateLimits['registration_attempt']['ip_max'] = 10;
$rateLimits['registration_attempt']['ip_window'] = 3600;
$rateLimits['registration_attempt']['total_max'] = 15;
$rateLimits['registration_attempt']['total_window'] = 3600;

$rateLimits['email_verification']['ip_max'] = 50;
$rateLimits['email_verification']['ip_window'] = 300;
$rateLimits['email_verification']['email_max'] = 4;
$rateLimits['email_verification']['email_window'] = 3600;
$rateLimits['email_verification']['total_max'] = 100;
$rateLimits['email_verification']['total_window'] = 300;

$rateLimits['registration_recovery_email']['ip_max'] = 5;
$rateLimits['registration_recovery_email']['ip_window'] = 3600;
$rateLimits['registration_recovery_email']['email_max'] = 3;
$rateLimits['registration_recovery_email']['email_window'] = 3600;
$rateLimits['registration_recovery_email']['total_max'] = 25;
$rateLimits['registration_recovery_email']['total_window'] = 3600;

$rateLimits['join_failure_beacon']['ip_max'] = 50;
$rateLimits['join_failure_beacon']['ip_window'] = 300;
$rateLimits['join_failure_beacon']['total_max'] = 100;
$rateLimits['join_failure_beacon']['total_window'] = 300;

$rateLimits['owner_contact_email']['ip_max'] = 50;
$rateLimits['owner_contact_email']['ip_window'] = 300;
$rateLimits['owner_contact_email']['user_max'] = 25;
$rateLimits['owner_contact_email']['user_window'] = 300;
$rateLimits['owner_contact_email']['total_max'] = 100;
$rateLimits['owner_contact_email']['total_window'] = 300;

$rateLimits['feedback_submission']['ip_max'] = 50;
$rateLimits['feedback_submission']['ip_window'] = 300;
$rateLimits['feedback_submission']['total_max'] = 100;
$rateLimits['feedback_submission']['total_window'] = 300;

$rateLimits['transfer_request']['ip_max'] = 50;
$rateLimits['transfer_request']['ip_window'] = 300;
$rateLimits['transfer_request']['user_max'] = 25;
$rateLimits['transfer_request']['user_window'] = 300;
$rateLimits['transfer_request']['total_max'] = 100;
$rateLimits['transfer_request']['total_window'] = 300;

$rateLimits['diagnostics']['ip_max'] = 50;
$rateLimits['diagnostics']['ip_window'] = 300;
$rateLimits['diagnostics']['user_max'] = 25;
$rateLimits['diagnostics']['user_window'] = 300;
$rateLimits['diagnostics']['total_max'] = 100;
$rateLimits['diagnostics']['total_window'] = 300;

$rateLimits['statistics_request']['ip_max'] = 50;
$rateLimits['statistics_request']['ip_window'] = 300;
$rateLimits['statistics_request']['user_max'] = 25;
$rateLimits['statistics_request']['user_window'] = 300;
$rateLimits['statistics_request']['total_max'] = 100;
$rateLimits['statistics_request']['total_window'] = 300;

// ip_max is PHP_INT_MAX by design: authenticated admin sessions are tracked
// reliably, so per-IP failure counting doesn't apply — total_max is what
// actually governs admin AJAX volume.
$rateLimits['admin_ajax_search']['ip_max'] = PHP_INT_MAX;
$rateLimits['admin_ajax_search']['ip_window'] = 300;
$rateLimits['admin_ajax_search']['total_max'] = 100;
$rateLimits['admin_ajax_search']['total_window'] = 300;

$rateLimits['admin_ajax_write']['ip_max'] = PHP_INT_MAX;
$rateLimits['admin_ajax_write']['ip_window'] = 300;
$rateLimits['admin_ajax_write']['total_max'] = 100;
$rateLimits['admin_ajax_write']['total_window'] = 300;

$rateLimits['location_search']['ip_max'] = PHP_INT_MAX;
$rateLimits['location_search']['ip_window'] = 60;
$rateLimits['location_search']['total_max'] = 10;
$rateLimits['location_search']['total_window'] = 60;

