#!/usr/bin/env bash
# Weekly launchd/cron script — checks installed UserSpice plugins against the
# upstream mudmin/usplugins monorepo and opens a GitHub issue if any are outdated.
#
# Setup:
#   1. Copy scripts/check-plugin-updates/check-plugin-updates.conf.example
#      to check-plugin-updates.conf in the same directory and fill in your values.
#   2. chmod +x check-plugin-updates.sh
#   3. Schedule via launchd (macOS) or cron.
#
# Requires: gh CLI authenticated (gh auth status), jq

set -uo pipefail

# Explicit PATH so launchd's minimal environment finds Homebrew tools
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SCRIPT_DIR/check-plugin-updates.conf"

if [[ ! -f "$CONF" ]]; then
    echo "Error: config file not found at $CONF" >&2
    echo "Copy check-plugin-updates.conf.example to check-plugin-updates.conf and fill in your values." >&2
    exit 1
fi

# shellcheck source=check-plugin-updates.conf.example
source "$CONF"

# Validate required config values
if [[ -z "${PROJECT_ROOT:-}" ]]; then
    echo "Error: PROJECT_ROOT is not set in $CONF" >&2
    exit 1
fi
if [[ -z "${GH_REPO:-}" ]]; then
    echo "Error: GH_REPO is not set in $CONF" >&2
    exit 1
fi

# Apply defaults for optional config values
UPSTREAM_REPO="${UPSTREAM_REPO:-mudmin/usplugins}"
PLUGINS_PATH="${PLUGINS_PATH:-usersc/plugins}"
ISSUE_LABEL="${ISSUE_LABEL:-plugin-update}"
ENVIRONMENTS="${ENVIRONMENTS:-Local}"

OUTDATED_NAMES=()
TABLE="| Plugin | Installed | Latest |\n|--------|-----------|--------|\n"

echo "[$(date '+%Y-%m-%d %H:%M')] Checking UserSpice plugin updates..."

for info_xml in "$PROJECT_ROOT/$PLUGINS_PATH"/*/info.xml; do
    [[ -f "$info_xml" ]] || continue

    plugin=$(basename "$(dirname "$info_xml")")

    LOCAL_VER=$(awk -F'[<>]' '/<version>/{gsub(/[[:space:]]/,"",$3); print $3; exit}' "$info_xml")
    [[ -z "$LOCAL_VER" ]] && continue

    # Fetch the full JSON response; gh api writes the body to stdout even on
    # 404s, so we extract .content with a separate jq call to get empty output
    # (not "null") for plugins absent from the upstream monorepo.
    RESPONSE=$(gh api "repos/$UPSTREAM_REPO/contents/src/$plugin/info.xml" 2>/dev/null || true)
    CONTENT=$(echo "$RESPONSE" | jq -r '.content // empty' 2>/dev/null || true)
    [[ -z "$CONTENT" ]] && continue

    UPSTREAM_VER=$(echo "$CONTENT" | base64 -D 2>/dev/null | \
        awk -F'[<>]' '/<version>/{gsub(/[[:space:]]/,"",$3); print $3; exit}') || true
    [[ -z "$UPSTREAM_VER" ]] && continue

    echo "  $plugin: local=$LOCAL_VER upstream=$UPSTREAM_VER"

    if [[ "$LOCAL_VER" != "$UPSTREAM_VER" ]]; then
        OUTDATED_NAMES+=("$plugin")
        TABLE+="| \`$plugin\` | \`$LOCAL_VER\` | \`$UPSTREAM_VER\` |\n"
    fi
done

if [[ ${#OUTDATED_NAMES[@]} -eq 0 ]]; then
    echo "All plugins are up to date."
    exit 0
fi

NAMES_STR=$(IFS=', '; echo "${OUTDATED_NAMES[*]}")
echo "Outdated: $NAMES_STR"

# Don't open a duplicate — one open issue at a time.
EXISTING=$(gh issue list \
    --repo "$GH_REPO" \
    --label "$ISSUE_LABEL" \
    --state open \
    --json number --jq 'length')

if [[ "$EXISTING" -gt 0 ]]; then
    echo "Open $ISSUE_LABEL issue already exists — skipping."
    exit 0
fi

# Ensure the label exists (idempotent).
gh label create "$ISSUE_LABEL" \
    --repo "$GH_REPO" \
    --description "Automated UserSpice plugin update notification" \
    --color "0075CA" 2>/dev/null || true

BODY_FILE=$(mktemp /tmp/plugin-update-body.XXXXXX.md)
trap 'rm -f "$BODY_FILE"' EXIT

printf "## UserSpice Plugin Updates Available\n\n%b\n" "$TABLE" > "$BODY_FILE"

# Build the environment checklist dynamically from config
{
    cat << 'HEADER'
## Manual Update Required

These plugins must be updated via **Spice Shaker** — there is nothing to merge or deploy automatically.

### Update checklist — all environments

HEADER
    for env in $ENVIRONMENTS; do
        echo "- [ ] $env"
    done
    cat << 'FOOTER'

**Steps per environment:** Admin → Spice Shaker → Installed Plugins → click Update on each plugin above → run any prompted migrations.

## Post-Deploy Note

Add to the post-deploy TODO for the next release:
> **Update UserSpice plugins via Spice Shaker** (see plugin table above).

---
*Generated by [scripts/check-plugin-updates.sh](scripts/check-plugin-updates.sh)*
FOOTER
} >> "$BODY_FILE"

gh issue create \
    --repo "$GH_REPO" \
    --title "chore: UserSpice plugin updates available ($NAMES_STR)" \
    --label "dependencies,$ISSUE_LABEL" \
    --body-file "$BODY_FILE"

echo "Issue opened for: $NAMES_STR"
