<?php

declare(strict_types=1);

/**
 * One-time migration helper for #1067 — reads `elan_admin_emails`/
 * `elan_feedback_email` from the live `settings` table row and appends them
 * to this environment's own `.env` as `ADMIN_EMAILS`/`FEEDBACK_EMAIL`
 * (preserving every existing key), then re-applies `chmod 600` to `.env`.
 *
 * The other 5 image-related settings this issue migrates
 * (elan_image_dir/_max/_upload_max_size/_display_max_size/
 * _thumbnail_sizes) were confirmed environment-by-environment via direct
 * DB queries during planning (values differed between prod and test for
 * elan_image_upload_max_size — 2 vs 3 — resolved to one constant, 3, as a
 * deliberate prod behavior change) and are hardcoded directly into
 * `usersc/includes/config.php` as a normal code change, not generated by
 * this script.
 *
 * Run once locally to verify, then once against test's own `.env`, then
 * once against prod's own `.env` — each already holds that environment's
 * own DB credentials. Delete this script from the repo once all three
 * environments are confirmed; it is a one-time tool, not kept as ongoing
 * deploy infrastructure.
 *
 * NOT idempotent: this only ever appends. Re-running it against a `.env`
 * that already has ADMIN_EMAILS/FEEDBACK_EMAIL adds a second, duplicate
 * pair of lines rather than erroring or updating in place — phpdotenv's
 * immutable loader is first-definition-wins, so the duplicate is silently
 * inert, not harmful, but it does leave stale-looking cruft in `.env`.
 * Check whether the keys are already present before re-running.
 *
 * Cannot live under app/admin/scripts/ — those require an authenticated
 * admin HTTP session via securePage(). This is a standalone CLI script
 * connecting directly via PDO, following scripts/log-deployment.php's
 * env-loading/connection pattern (no full UserSpice bootstrap).
 *
 * This tool is meant to be run and read interactively by a human, so unlike
 * log-deployment.php's "never fail the caller" contract, failures here are
 * allowed to surface with a full error message and a non-zero exit — the
 * whole point is for the operator to see exactly what went wrong.
 *
 * Usage: php scripts/generate-config.php
 */

require_once __DIR__ . '/../vendor/autoload.php';

$projectRoot = dirname(__DIR__);
if (file_exists($projectRoot . '/.env')) {
    \Dotenv\Dotenv::createImmutable($projectRoot)->safeLoad();
}

foreach (['DB_NAME', 'DB_USER', 'DB_PASS'] as $requiredVar) {
    if (($_ENV[$requiredVar] ?? getenv($requiredVar) ?: '') === '') {
        fwrite(STDERR, "Required environment variable '$requiredVar' is not set.\n");
        exit(1);
    }
}

// DB_HOST may carry an embedded port (e.g. local MAMP: "127.0.0.1:8889")
// in addition to — or instead of — a separate DB_PORT. Split it out so
// both the plain-host (production/dev) and host:port (local) .env forms
// connect correctly. Mirrors scripts/log-deployment.php exactly.
$dbHostRaw = (string)($_ENV['DB_HOST'] ?? getenv('DB_HOST') ?: 'localhost');
$dbPort = (int)($_ENV['DB_PORT'] ?? getenv('DB_PORT') ?: 3306);
if (str_contains($dbHostRaw, ':')) {
    [$dbHost, $hostPort] = explode(':', $dbHostRaw, 2);
    $dbPort = (int)$hostPort;
} else {
    $dbHost = $dbHostRaw;
}
// 'localhost' resolves to a Unix socket path on macOS that differs between
// CLI PHP and MAMP, causing connection failures. Force TCP instead.
if ($dbHost === 'localhost') {
    $dbHost = '127.0.0.1';
}
$dbName = (string)($_ENV['DB_NAME'] ?? getenv('DB_NAME'));
$dbUser = (string)($_ENV['DB_USER'] ?? getenv('DB_USER'));
$dbPass = (string)($_ENV['DB_PASS'] ?? getenv('DB_PASS'));

try {
    $pdo = new PDO(
        "mysql:host=$dbHost;port=$dbPort;dbname=$dbName;charset=utf8mb4",
        $dbUser,
        $dbPass,
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
} catch (\PDOException $e) {
    fwrite(STDERR, 'Database connection failed: ' . $e->getMessage() . "\n");
    exit(1);
}

$statement = $pdo->query(
    'SELECT elan_admin_emails, elan_feedback_email FROM settings WHERE id = 1'
);
$row = $statement !== false ? $statement->fetch(PDO::FETCH_ASSOC) : false;

if ($row === false) {
    fwrite(STDERR, "No settings row found (id = 1). Nothing to generate.\n");
    exit(1);
}

// A NULL column (never set by any migration, only a column-level default —
// see this script's docblock) must fail loudly here, not silently coerce to
// an empty string. custom_functions.php's read-time fallback would mask an
// empty .env value at runtime, but this write-time check exists so the
// operator sees the real problem instead of both layers quietly assuming
// the other one caught it.
if ($row['elan_admin_emails'] === null || $row['elan_feedback_email'] === null) {
    fwrite(STDERR, "elan_admin_emails or elan_feedback_email is NULL in the settings row — refusing to write an empty value to .env. Set the column directly or investigate why it was never populated.\n");
    exit(1);
}

$adminEmails = (string)$row['elan_admin_emails'];
$feedbackEmail = (string)$row['elan_feedback_email'];

// .env is KEY=value, not PHP — always double-quote and escape the captured
// value (never conditionally), since a DB value containing a literal
// newline (e.g. "x\nADMIN_EMAILS=evil@attacker.com") would otherwise be
// written unquoted and parsed by vlucas/phpdotenv as a SEPARATE, overriding
// KEY=value line on next load — a value-injection path from anyone with
// write access to the settings.elan_admin_emails/elan_feedback_email
// columns into this script's own operator-controlled .env. Escaping
// backslash, double-quote, CR, and LF closes that path; matches how quoted
// values already appear elsewhere in this repo's .env files (e.g.
// TEST_PASSWORD).
$formatEnvValue = static fn(string $v) => '"' . str_replace(
    ['\\', '"', "\r", "\n"],
    ['\\\\', '\\"', '\\r', '\\n'],
    $v
) . '"';

$envPath = $projectRoot . '/.env';
if (!file_exists($envPath)) {
    fwrite(STDERR, "$envPath does not exist — nothing to append to. Aborting before any write.\n");
    exit(1);
}

$envAppend = "\n# Added by scripts/generate-config.php (#1067)\n"
    . 'ADMIN_EMAILS=' . $formatEnvValue($adminEmails) . "\n"
    . 'FEEDBACK_EMAIL=' . $formatEnvValue($feedbackEmail) . "\n";

if (file_put_contents($envPath, $envAppend, FILE_APPEND | LOCK_EX) === false) {
    fwrite(STDERR, "Failed to write to $envPath.\n");
    exit(1);
}
chmod($envPath, 0600);

echo "Appended ADMIN_EMAILS/FEEDBACK_EMAIL to $envPath (chmod 600 re-applied).\n";
echo "Values written: ADMIN_EMAILS=" . $formatEnvValue($adminEmails)
    . ", FEEDBACK_EMAIL=" . $formatEnvValue($feedbackEmail) . "\n";

exit(0);
